### ISSUE TITLE
pip install needs appdirs

### ISSUE THREAD

**Issue by cbyrohl** [norok2/flyingcircus#2]
Hi there,

I get the following error on installing flyingcircus from commit d9805caf314e4310bd2847a333e8d5548be9fa0e via `pip install:`
```
  Cloning https://github.com/cbyrohl/flyingcircus.git to /tmp/pip-req-build-tx_m8xok
  Running command git clone -q https://github.com/cbyrohl/flyingcircus.git /tmp/pip-req-build-tx_m8xok
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-tx_m8xok/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-tx_m8xok/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_5f5kqi2
         cwd: /tmp/pip-req-build-tx_m8xok/
    Complete output (16 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-_5f5kqi2/flyingcircus.egg-info
    writing /tmp/pip-pip-egg-info-_5f5kqi2/flyingcircus.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-_5f5kqi2/flyingcircus.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-pip-egg-info-_5f5kqi2/flyingcircus.egg-info/entry_points.txt
    writing requirements to /tmp/pip-pip-egg-info-_5f5kqi2/flyingcircus.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-_5f5kqi2/flyingcircus.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-_5f5kqi2/flyingcircus.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-_5f5kqi2/flyingcircus.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-tx_m8xok/setup.py", line 181, in <module>
        from flyingcircus import pkg_paths
      File "/tmp/pip-req-build-tx_m8xok/flyingcircus/__init__.py", line 19, in <module>
        import appdirs  # Determine appropriate platform-specific dirs
    ModuleNotFoundError: No module named 'appdirs'
```

The problem is fixed with commit https://github.com/cbyrohl/flyingcircus/commit/b7d7993cc3fe8f18ff22c4d20d4232736a683d66.

I produced the error in the following environment:
```
FROM debian:bullseye 

RUN apt-get -y -qq update && \
    apt-get -y -qq upgrade && \
    apt-get -y -qq install git cmake gcc g++ libopenmpi-dev libhdf5-openmpi-dev cppcheck && \
    apt-get -y -qq install python3 python3-matplotlib python3-numpy python3-h5py python3-astropy python3-pip

RUN apt-get install -y -qq gnupg2 lsb-release wget && \
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null && \
    echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ bionic main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null && \
    apt-get -y -qq update && \
    apt-get -y -qq  install cmake  && \
    apt-get -y -qq clean && \
    rm -rf /var/lib/apt/lists/*
```

**Comment by norok2** [comment]
Thanks for fixing this! If you want to submit a PR for this, I'll approve it right away.
